version: '3.8'

services:
    php:
        container_name: ${PROJECT_NAME}-php
        image: hub.iomedia.ch/php_81:node16
        expose:
            - 9001 # xdebug port
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            - PHP_IDE_CONFIG=serverName=docker
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_HOST
            - MYSQL_DATABASE
            - MYSQL_PORT
            - MYSQL_ROOT_PASSWORD
            - SSH_AUTH_SOCK=$SSH_AUTH_SOCKET #required for linux
            - PANTHER_NO_SANDBOX
            - PANTHER_CHROME_ARGUMENTS
        volumes:
            - ./:/var/www:rw,cached
            - app:/var/www/var/cache
            - ./var/logs:/var/www/var/logs:rw,delegated
            - ./node_modules:/var/www/node_modules:rw,delegated
            - ./vendor:/var/www/vendor:rw,delegated
            - $SSH_AUTH_SOCKET:$SSH_AUTH_SOCKET
        networks:
            - default
    http:
        container_name: ${PROJECT_NAME}-http
        image: hub.iomedia.ch/apache_24_flex
        expose:
            - 80 # http port
            - 443 # https port
        volumes:
            - ./:/var/www:rw,cached
        depends_on:
            - php
        labels:
            - 'traefik.frontend.rule=Host:back.${PROJECT_NAME}.localhost'
            - 'traefik.enable=true'
        networks:
            - traefik
            - default
    db:
        container_name: ${PROJECT_NAME}-db
        image: hub.iomedia.ch/mysql_57
        expose:
            - 3306 # mysql port
        ports:
            - '3306'
        volumes:
            - database:/var/lib/mysql:rw,delegated
        environment:
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD
        labels:
            - 'traefik.frontend.rule=Host:db.${PROJECT_NAME}.localhost'
            - 'traefik.enable=true'
        networks:
            - traefik
            - default
    mail:
        container_name: ${PROJECT_NAME}-mail
        image: schickling/mailcatcher
        labels:
            - 'traefik.frontend.rule=Host:mail.${PROJECT_NAME}.localhost'
            - 'traefik.enable=true'
            - 'traefik.port=1080'
        networks:
            - traefik
            - default
    adminer:
        container_name: ${PROJECT_NAME}-adminer
        image: adminer
        expose:
            - 8080
        restart: always
        environment:
            - ADMINER_PLUGINS=tables-filter tinymce edit-calendar
            - ADMINER_DESIGN=pepa-linha
        labels:
            - 'traefik.frontend.rule=Host:adminer.${PROJECT_NAME}.localhost'
            - 'traefik.enable=true'
            - 'traefik.port=8080'
        networks:
            - traefik
            - default

volumes:
    app:
    database:

networks:
    traefik:
        external: true
